version: "2"
services:
    common_master_1:
        image: mysql:5.7.27
        container_name: ${MASTER_1_HOSTNAME}
        hostname: ${MASTER_1_HOSTNAME}
        volumes:
            - ../conf/master1.cnf:/etc/mysql/conf.d/my.cnf:ro
            - ../data/master1:/var/lib/mysql:rw
            - /usr/share/zoneinfo/:/usr/share/zoneinfo/:ro
        environment:
            MYSQL_ROOT_PASSWORD: ${MASTER_1_ROOT_PASSWORD}
        networks:
            replication_network:
                ipv4_address: ${MASTER_1_HOST_IP}
        ports:
            - 3316:3306
    common_slave_1:
        image: mysql:5.7.27
        container_name: ${SLAVE_1_HOSTNAME}
        hostname: ${SLAVE_1_HOSTNAME}
        volumes:
            - ../conf/slave1.cnf:/etc/mysql/conf.d/my.cnf:ro
            - ../data/slave1:/var/lib/mysql:rw
            - /usr/share/zoneinfo/:/usr/share/zoneinfo/:ro
        environment:
            MYSQL_ROOT_PASSWORD: ${SLAVE_1_ROOT_PASSWORD}
        networks:
            replication_network:
                ipv4_address: ${SLAVE_1_HOST_IP}
        ports:
            - 3326:3306
    common_master_2:
        container_name: ${MASTER_2_HOSTNAME}
        image: mysql:5.7.27
        hostname: ${MASTER_2_HOSTNAME}
        volumes:
            - ../conf/master2.cnf:/etc/mysql/conf.d/my.cnf:ro
            - ../data/master2:/var/lib/mysql:rw
            - /usr/share/zoneinfo/:/usr/share/zoneinfo/:ro
        environment:
            MYSQL_ROOT_PASSWORD: ${MASTER_2_ROOT_PASSWORD}
        networks:
            replication_network:
                ipv4_address: ${MASTER_2_HOST_IP}
    common_slave_2:
        image: mysql:5.7.27
        container_name: ${SLAVE_2_HOSTNAME}
        hostname: ${SLAVE_2_HOSTNAME}
        volumes:
            - ../conf/slave2.cnf:/etc/mysql/conf.d/my.cnf:ro
            - ../data/slave2:/var/lib/mysql:rw
            - /usr/share/zoneinfo/:/usr/share/zoneinfo/:ro
        environment:
            MYSQL_ROOT_PASSWORD: ${SLAVE_2_ROOT_PASSWORD}
        networks:
            replication_network:
                ipv4_address: ${SLAVE_2_HOST_IP}
    replication:
        image: ubuntu:18.04
        volumes:
            - ../scripts:${REPL_SCRIPT_MOUNT_PATH}
        networks:
            - replication_network
        environment:
            MASTER_1_HOSTNAME: ${MASTER_1_HOSTNAME}
            MASTER_1_HOST_IP: ${MASTER_1_HOST_IP}
            MASTER_1_ROOT_USER: ${MASTER_1_ROOT_USER}
            MASTER_1_ROOT_PASSWORD: ${MASTER_1_ROOT_PASSWORD}

            SLAVE_1_HOSTNAME: ${SLAVE_1_HOSTNAME}
            SLAVE_1_HOST_IP: ${SLAVE_1_HOST_IP}
            SLAVE_1_ROOT_USER: ${SLAVE_1_ROOT_USER}
            SLAVE_1_ROOT_PASSWORD: ${SLAVE_1_ROOT_PASSWORD}

            MASTER_2_HOSTNAME: ${MASTER_2_HOSTNAME}
            MASTER_2_HOST_IP: ${MASTER_2_HOST_IP}
            MASTER_2_ROOT_USER: ${MASTER_2_ROOT_USER}
            MASTER_2_ROOT_PASSWORD: ${MASTER_2_ROOT_PASSWORD}

            SLAVE_2_HOSTNAME: ${SLAVE_2_HOSTNAME}
            SLAVE_2_HOST_IP: ${SLAVE_2_HOST_IP}
            SLAVE_2_ROOT_USER: ${SLAVE_2_ROOT_USER}
            SLAVE_2_ROOT_PASSWORD: ${SLAVE_2_ROOT_PASSWORD}

            REPL_USER: ${REPL_USER}
            REPL_PASSWORD: ${REPL_PASSWORD}
        command: bash ${REPL_SCRIPT_MOUNT_PATH}/slave-2-master-2-master-2-slave.sh
    pma:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        hostname: phpmyadmin
        environment:
            - PMA_ARBITRARY=1
        restart: always
        ports:
            - 8080:80
        volumes:
            - /sessions
        networks:
            - replication_network
